begin;
drop table if exists playground;
drop table if exists transaction_splits;
drop table if exists transactions;
drop table if exists shared_transactions;
drop table if exists categories;
drop table if exists frames;
drop table if exists membership;
drop table if exists groups;
drop table if exists friendship;
drop table if exists users;
drop table if exists session;
commit;
