begin;
drop table if exists playground;
drop table if exists transactions;
drop table if exists categories;
drop table if exists income;
drop table if exists frames;
drop table if exists membership;
drop table if exists groups;
drop table if exists users;
commit;
